//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eclipse2Game.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TutorialStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TutorialStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eclipse2Game.Strings.TutorialStrings", typeof(TutorialStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain! Oh Captain!
        ///You are the greatest captain to ever live!.
        /// </summary>
        internal static string IntroString01 {
            get {
                return ResourceManager.GetString("IntroString01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erm... what was your name again?
        ///: .
        /// </summary>
        internal static string IntroString02 {
            get {
                return ResourceManager.GetString("IntroString02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thats right! Captain {0}! What a sexy name!
        ///And I am your Commanding officer/lover, Admiral Juniper..
        /// </summary>
        internal static string IntroString03 {
            get {
                return ResourceManager.GetString("IntroString03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh, and I have completely forgotten, what is your ship called?
        ///: .
        /// </summary>
        internal static string IntroString04 {
            get {
                return ResourceManager.GetString("IntroString04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ah yes... {0}.  Never has there been a finer ship in all of the hexiverse..
        /// </summary>
        internal static string IntroString05 {
            get {
                return ResourceManager.GetString("IntroString05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been in hypersleep for quite some time.  Do you need a quick flying lesson?.
        /// </summary>
        internal static string IntroString06 {
            get {
                return ResourceManager.GetString("IntroString06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I need a tutorial of sorts!.
        /// </summary>
        internal static string IntroString06_1 {
            get {
                return ResourceManager.GetString("IntroString06_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I am the best captain in the hexiverse!.
        /// </summary>
        internal static string IntroString06_2 {
            get {
                return ResourceManager.GetString("IntroString06_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Tutorial.
        /// </summary>
        internal static string TutorialString01 {
            get {
                return ResourceManager.GetString("TutorialString01", resourceCulture);
            }
        }
    }
}
